### ISSUE TITLE
ErrorException: Undefined index: notification_level

### ISSUE THREAD

**Issue by cromefire** [nextcloud/spreed#1430]
## Steps to reproduce
1. Access
2. Get error

### Expected behaviour
```
ErrorException: Undefined index: notification_level
#12 spreed/lib/Manager.php(124): handleError
#11 spreed/lib/Manager.php(124): createParticipantObject
#10 spreed/lib/Room.php(836): getParticipants
#9 spreed/lib/Controller/RoomController.php(247): formatRoom
#8 spreed/lib/Controller/RoomController.php(132): getRooms
#7 /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php(166): executeController
#6 /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php(99): dispatch
#5 /var/www/nextcloud/lib/private/AppFramework/App.php(118): main
#4 /var/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php(47): __invoke
#3 /var/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php(0): call_user_func
#2 /var/www/nextcloud/lib/private/Route/Router.php(297): match
#1 /var/www/nextcloud/ocs/v1.php(82): require_once
#0 /var/www/nextcloud/ocs/v2.php(24): null
```

### Actual behaviour
No error

## Browser

**Microphone available:** N/A

**Camera available:** N/A

**Operating system:** N/A

**Browser name:** N/A

**Browser version:** N/A

### Browser log
N/A

## Spreed app

**Spreed app version:** 5.0.0 (see apps admin page: `/settings/apps`)

**Custom TURN server configured:** yes (see additional admin settings: `/settings/admin/talk`)

**Custom STUN server configured:** yes (see additional admin settings: `/settings/admin/talk`)

## Server configuration

**Operating system**: Ubuntu 18.04

**Web server:** Apache 2.4

**Database:** Maria

**PHP version:** 7.2

**Nextcloud Version:** (see admin page)

**List of activated apps:**

<details>

```
Enabled:
  - accessibility: 1.1.0
  - activity: 2.8.2
  - audioplayer: 2.5.1
  - bruteforcesettings: 1.3.0
  - checksum: 0.4.2
  - cloud_federation_api: 0.1.0
  - comments: 1.5.0
  - contacts: 3.0.1
  - dav: 1.8.0
  - encryption: 2.3.0
  - federatedfilesharing: 1.5.0
  - federation: 1.5.0
  - files: 1.10.0
  - files_external: 1.6.0
  - files_fulltextsearch: 1.2.3
  - files_markdown: 2.0.5
  - files_mindmap: 0.0.11
  - files_pdfviewer: 1.4.0
  - files_sharing: 1.7.0
  - files_texteditor: 2.7.0
  - files_trashbin: 1.5.0
  - files_versions: 1.8.0
  - files_videoplayer: 1.4.0
  - firstrunwizard: 2.4.0
  - fulltextsearch: 1.2.3
  - fulltextsearch_elasticsearch: 1.2.2
  - gallery: 18.2.0
  - jsloader: 1.0.2
  - logreader: 2.0.0
  - lookup_server_connector: 1.3.0
  - mail: 0.11.0
  - nextcloud_announcements: 1.4.0
  - notes: 2.5.1
  - notifications: 2.3.0
  - oauth2: 1.3.0
  - password_policy: 1.5.0
  - polls: 0.9.5
  - provisioning_api: 1.5.0
  - richdocuments: 3.1.0
  - sentry: 4.0.0
  - serverinfo: 1.5.0
  - sharebymail: 1.5.0
  - spreed: 5.0.0
  - support: 1.0.0
  - survey_client: 1.3.0
  - systemtags: 1.5.0
  - tasks: 0.9.8
  - theming: 1.6.0
  - twofactor_backupcodes: 1.4.1
  - unsplash: 1.1.3
  - updatenotification: 1.5.0
  - workflowengine: 1.5.0
```

</details>

**Nextcloud configuration:**

<details>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "15.0.0.10",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "htaccess.RewriteBase": "\/",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "twofactor_enforced": "false",
        "twofactor_enforced_groups": [],
        "twofactor_enforced_excluded_groups": [],
        "memcache.local": "\\OC\\Memcache\\Memcached",
        "memcache.distributed": "\\OC\\Memcache\\Memcached",
        "memcached_servers": [
            [
                "localhost",
                11211
            ]
        ],
        "filelocking.enabled": true,
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "dbindex": 1,
            "timeout": 1.5,
            "password": "***REMOVED SENSITIVE VALUE***"
        },
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_smtpsecure": "ssl",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "sentry.dsn": "***REMOVED SENSITIVE VALUE***",
        "sentry.public-dsn": "***REMOVED SENSITIVE VALUE***",
        "updater.release.channel": "production"
    }
}
```

</details>

<br/>
I can privately share a link to the sentry reports (there are 3k of events)

**Comment by cromefire** [comment]
Maybe related:

<details>

```
PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'notification_level' in 'field list'
#15 /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php(105): execute
#14 /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php(105): execute
#13 /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(1006): executeUpdate
#12 /var/www/nextcloud/lib/private/DB/Connection.php(216): executeUpdate
#11 /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php(208): execute
#10 /var/www/nextcloud/lib/private/DB/QueryBuilder/QueryBuilder.php(214): execute
#9 spreed/lib/Participant.php(163): setNotificationLevel
#8 spreed/lib/Controller/RoomController.php(611): setNotificationLevel
#7 /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php(166): executeController
#6 /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php(99): dispatch
#5 /var/www/nextcloud/lib/private/AppFramework/App.php(118): main
#4 /var/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php(47): __invoke
#3 /var/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php(0): call_user_func
#2 /var/www/nextcloud/lib/private/Route/Router.php(297): match
#1 /var/www/nextcloud/ocs/v1.php(82): require_once
#0 /var/www/nextcloud/ocs/v2.php(24): null

Doctrine\DBAL\Driver\PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'notification_level' in 'field list'
#14 /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php(107): execute
#13 /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(1006): executeUpdate
#12 /var/www/nextcloud/lib/private/DB/Connection.php(216): executeUpdate
#11 /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php(208): execute
#10 /var/www/nextcloud/lib/private/DB/QueryBuilder/QueryBuilder.php(214): execute
#9 spreed/lib/Participant.php(163): setNotificationLevel
#8 spreed/lib/Controller/RoomController.php(611): setNotificationLevel
#7 /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php(166): executeController
#6 /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php(99): dispatch
#5 /var/www/nextcloud/lib/private/AppFramework/App.php(118): main
#4 /var/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php(47): __invoke
#3 /var/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php(0): call_user_func
#2 /var/www/nextcloud/lib/private/Route/Router.php(297): match
#1 /var/www/nextcloud/ocs/v1.php(82): require_once
#0 /var/www/nextcloud/ocs/v2.php(24): null

Doctrine\DBAL\Exception\InvalidFieldNameException: An exception occurred while executing 'UPDATE `oc_talk_participants` SET `notification_level` = ? WHERE (`user_id` = ?) AND (`room_id` = ?)' with params [2, "tim", 1]:

SQLSTATE[42S22]: Column not found: 1054 Unknown column 'notification_level' in 'field list'
#15 /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php(71): convertException
#14 /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(128): driverExceptionDuringQuery
#13 /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(1015): executeUpdate
#12 /var/www/nextcloud/lib/private/DB/Connection.php(216): executeUpdate
#11 /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php(208): execute
#10 /var/www/nextcloud/lib/private/DB/QueryBuilder/QueryBuilder.php(214): execute
#9 spreed/lib/Participant.php(163): setNotificationLevel
#8 spreed/lib/Controller/RoomController.php(611): setNotificationLevel
#7 /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php(166): executeController
#6 /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php(99): dispatch
#5 /var/www/nextcloud/lib/private/AppFramework/App.php(118): main
#4 /var/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php(47): __invoke
#3 /var/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php(0): call_user_func
#2 /var/www/nextcloud/lib/private/Route/Router.php(297): match
#1 /var/www/nextcloud/ocs/v1.php(82): require_once
#0 /var/www/nextcloud/ocs/v2.php(24): null
```

</details>

**Comment by nickvergessen** [comment]
This implies that your database was not updated correctly.

Can you check your oc_migrations table whether there are entries starting eith OCA\Spreed

**Comment by cromefire** [comment]
I thought so is there a command, which automatically applies migrations?
Or can you give me a SQL command which adds that column? (Or at least table & type)

**Comment by cromefire** [comment]
And yes there are spreed entries:

```
spreed	2000Date20170707093535
spreed	2000Date20171026140256
spreed	2000Date20171026140257
spreed	2001Date20170707115443
spreed	2001Date20170913104501
spreed	2001Date20170921145301
spreed	2001Date20170929092606
spreed	2001Date20171009132424
spreed	2001Date20171026134605
spreed	2001Date20171026141336
spreed	2001Date20171031102049
spreed	2001Date20180103144447
spreed	2001Date20180103150836
spreed	3002Date20180319104030
spreed	3003Date20180707222130
spreed	3003Date20180718112436
spreed	3003Date20180718133519
spreed	3003Date20180720162342
spreed	3003Date20180722152733
spreed	3003Date20180722152849
spreed	3003Date20180730080327
spreed	4099Date20181001123058
```

**Comment by cromefire** [comment]
I dropped the `oc_talk_*` tables, removed all entries for spreed in `oc_migrations` and fully removed and reinstalled spreed.
If someone else has this problem, I recommend to **first** uninstall it, else you get a bunch of errors.

**Comment by ostasevych** [comment]
> I dropped the `oc_talk_*` tables, removed all entries for spreed in `oc_migrations` and fully removed and reinstalled spreed.
> If someone else has this problem, I recommend to **first** uninstall it, else you get a bunch of errors.

After doing this I found that there were certain relations in notifications, and now one of users has in the list of chats the notifications with Talk updates... Plus, there's observed duplication of users: some users, whom I would like to share smth are shown twice: ordinary and with the suffix (conversation).... 

May that be possible fixed somehow?

**Comment by nickvergessen** [comment]
Remove all entries of oc_share with share_type 10 and 11.
And for notifications with object_type call, chat and room.
You also need to remove the chat messages from the oc_comments table with object_type chat.
And much more.

But well actually you should not have done this at all.

**Comment by ostasevych** [comment]
> Remove all entries of oc_share with share_type 10 and 11.
> And for notifications with object_type call, chat and room.
> You also need to remove the chat messages from the oc_comments table with object_type chat.
> And much more.
> 
> But well actually you should not have done this at all.

Thank you a lot!
