### ISSUE TITLE
screen sharing not working

### ISSUE THREAD

**Issue by mokkin** [nextcloud/spreed#2377]
### Expected behaviour
screen sharing should work
### Actual behaviour
Sharing of another window (Firefox, LibreOffice) doesn't work. The other attendee is only seein a question mark on a black background.
The video transmission in both ways is okay.

## Browser
Chromium 
**Microphone available:** yes/no
no
**Camera available:** yes/no
yes
**Operating system:** Windows/Ubuntu/...
Manjaro Linux 18.1 x64 Gnome
**Browser name:** Firefox/Chrome/...
Chromium
**Browser version:** 50.1/55/...
Version 77.0.3865.120 (Offizieller Build) Arch Linux (64-Bit)

## Talk app

**Talk app version:** (see apps admin page: `/index.php/settings/apps`)
6.0.4
**Custom TURN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/additional`)
stun.nextcloud.com:443
**Custom STUN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/additional`)
yes, coturn on a local Debian server. Server test says "ok".

## Server configuration

**Operating system**: Ubuntu/RedHat/...
Plesk on Debian
**Web server:** Apache/Nginx
Apache+Nginx (no acces, shared hosting on netcup)
**Database:** MySQL/Maria/SQLite/PostgreSQL
mysql  Ver 15.1 Distrib 10.0.38-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
**PHP version:**
7.3.9
**Nextcloud Version:** (see admin page)
16.0.5
**List of activated apps:**

<details>
```
php occ app:list
PHP Warning:  fileperms(): stat failed for /var/www/vhosts/hosting123456.abcde.netcup.net/httpdocs/cloud/data/nextcloud.log in /httpdocs/cloud/lib/private/Log/File.php on line 140
{"reqId":"YDfKA14GdSauccd3EUGc","level":3,"time":"2019-10-29T19:44:36+01:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"fileperms(): stat failed for \/var\/www\/vhosts\/hosting123456.abcde.netcup.net\/httpdocs\/cloud\/data\/nextcloud.log at \/httpdocs\/cloud\/lib\/private\/Log\/File.php#140","userAgent":"--","version":"16.0.5.1"}
{"reqId":"YDfKA14GdSauccd3EUGc","level":2,"time":"2019-10-29T19:44:36+01:00","remoteAddr":"","user":"--","app":"no app in context","method":"","url":"--","message":"Temporary directory \/var\/www\/vhosts\/hosting123456.abcde.netcup.net\/tmp\/nc is not present or writable","userAgent":"--","version":"16.0.5.1"}
The current PHP memory limit is below the recommended value of 512MB.
Dein Datenverzeichnis ist ungültig
Stelle sicher, dass eine Datei ".ocdata" im Wurzelverzeichnis des data-Verzeichnisses existiert.

Kann das "Daten"-Verzeichnis nicht erstellen
Dies kann zumeist behoben werden, indem dem Web-Server Schreibzugriff auf das Wurzel-Verzeichnis eingeräumt wird. Siehe auch https://docs.nextcloud.com/server/16/go.php?to=admin-dir_permissions

An unhandled exception has been thrown:
Exception: Environment not properly prepared. in /httpdocs/cloud/lib/private/Console/Application.php:166
Stack trace:
#0 /httpdocs/cloud/console.php(96): OC\Console\Application->loadCommands(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#1 /httpdocs/cloud/occ(11): require_once('/httpdocs/cloud...')
#2 {main}PHP Warning:  fileperms(): stat failed for /var/www/vhosts/hosting123456.abcde.netcup.net/httpdocs/cloud/data/nextcloud.log in /httpdocs/cloud/lib/private/Log/File.php on line 140
{"reqId":"YDfKA14GdSauccd3EUGc","level":3,"time":"2019-10-29T19:44:36+01:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"fileperms(): stat failed for \/var\/www\/vhosts\/hosting123456.abcde.netcup.net\/httpdocs\/cloud\/data\/nextcloud.log at \/httpdocs\/cloud\/lib\/private\/Log\/File.php#140","userAgent":"--","version":"16.0.5.1"}
{"reqId":"YDfKA14GdSauccd3EUGc","level":3,"time":"2019-10-29T19:44:36+01:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"chmod(): No such file or directory at \/httpdocs\/cloud\/lib\/private\/Log\/File.php#141","userAgent":"--","version":"16.0.5.1"}

```
</details>

**Nextcloud configuration:**

<details>
```
php occ config:list system
PHP Warning:  fileperms(): stat failed for /var/www/vhosts/hosting123456.abcde.netcup.net/httpdocs/cloud/data/nextcloud.log in /httpdocs/cloud/lib/private/Log/File.php on line 140
{"reqId":"1dsugGogcmCWJUeAEG3U","level":3,"time":"2019-10-29T19:34:46+01:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"fileperms(): stat failed for \/var\/www\/vhosts\/hosting123456.abcde.netcup.net\/httpdocs\/cloud\/data\/nextcloud.log at \/httpdocs\/cloud\/lib\/private\/Log\/File.php#140","userAgent":"--","version":"16.0.5.1"}
{"reqId":"1dsugGogcmCWJUeAEG3U","level":2,"time":"2019-10-29T19:34:46+01:00","remoteAddr":"","user":"--","app":"no app in context","method":"","url":"--","message":"Temporary directory \/var\/www\/vhosts\/hosting123456.abcde.netcup.net\/tmp\/nc is not present or writable","userAgent":"--","version":"16.0.5.1"}
The current PHP memory limit is below the recommended value of 512MB.
Dein Datenverzeichnis ist ungültig
Stelle sicher, dass eine Datei ".ocdata" im Wurzelverzeichnis des data-Verzeichnisses existiert.

Kann das "Daten"-Verzeichnis nicht erstellen
Dies kann zumeist behoben werden, indem dem Web-Server Schreibzugriff auf das Wurzel-Verzeichnis eingeräumt wird. Siehe auch https://docs.nextcloud.com/server/16/go.php?to=admin-dir_permissions

An unhandled exception has been thrown:
Exception: Environment not properly prepared. in /httpdocs/cloud/lib/private/Console/Application.php:166
Stack trace:
#0 /httpdocs/cloud/console.php(96): OC\Console\Application->loadCommands(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#1 /httpdocs/cloud/occ(11): require_once('/httpdocs/cloud...')
#2 {main}PHP Warning:  fileperms(): stat failed for /var/www/vhosts/hosting123456.abcde.netcup.net/httpdocs/cloud/data/nextcloud.log in /httpdocs/cloud/lib/private/Log/File.php on line 140
{"reqId":"1dsugGogcmCWJUeAEG3U","level":3,"time":"2019-10-29T19:34:48+01:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"fileperms(): stat failed for \/var\/www\/vhosts\/hosting123456.abcde.netcup.net\/httpdocs\/cloud\/data\/nextcloud.log at \/httpdocs\/cloud\/lib\/private\/Log\/File.php#140","userAgent":"--","version":"16.0.5.1"}
{"reqId":"1dsugGogcmCWJUeAEG3U","level":3,"time":"2019-10-29T19:34:48+01:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"chmod(): No such file or directory at \/httpdocs\/cloud\/lib\/private\/Log\/File.php#141","userAgent":"--","version":"16.0.5.1"}

```
</details>

### Server log (data/nextcloud.log)
<details>
```
no entries while problems occure
```
</details>

**Comment by nickvergessen** [comment]
Did you install the necessary extension?

**Comment by scroom** [comment]
@nickvergessen Just stumbled across this bug report. Would it be possible to see if the necessary extension is available and inform the user that this might not be the case?

**Comment by nickvergessen** [comment]
Code is still there:
https://github.com/nextcloud/spreed/blob/master/src/components/CallView/LocalMediaControls.vue#L331-L341

But you should see an error message being shown when trying to share your screen
