### ISSUE TITLE
"ping" not working

### ISSUE THREAD

**Issue by fancycode** [nextcloud/spreed#359]
Since #349, a client regularly "pings" a call by sending a `PUT` to `/api/{apiVersion}/call/{token}`. As no body is sent with the request, the server logs an error and the request is ignored - causing clients to get disconnected after 30 seconds.

This is the error in `nextcloud.log`:
```
{"reqId":"JlPbWzOMrTFnX0viGqJD","level":3,"time":"2017-07-13T13:28:20+00:00","remoteAddr":"10.1.1.31","user":"user","app":"no app in context","method":"PUT","url":"\/ocs\/v2.php\/apps\/spreed\/api\/v1\/call\/4wum","message":"Exception: {\"Exception\":\"LogicException\",\"Message\":\"\\\"put\\\" can only be accessed once if not application\\\/x-www-form-urlencoded or application\\\/json.\",\"Code\":0,\"Trace\":\"#0 \\\/srv\\\/www\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Request.php(271): OC\\\\AppFramework\\\\Http\\\\Request->getContent()\\n#1 \\\/srv\\\/www\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Request.php(341): OC\\\\AppFramework\\\\Http\\\\Request->__get('parameters')\\n#2 \\\/srv\\\/www\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(166): OC\\\\AppFramework\\\\Http\\\\Request->getParam('format')\\n#3 \\\/srv\\\/www\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(90): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\Spreed\\\\Controller\\\\CallController), 'pingCall')\\n#4 \\\/srv\\\/www\\\/lib\\\/private\\\/AppFramework\\\/App.php(114): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Spreed\\\\Controller\\\\CallController), 'pingCall')\\n#5 \\\/srv\\\/www\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(47): OC\\\\AppFramework\\\\App::main('OCA\\\\\\\\Spreed\\\\\\\\Cont...', 'pingCall', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#6 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#7 \\\/srv\\\/www\\\/lib\\\/private\\\/Route\\\/Router.php(299): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#8 \\\/srv\\\/www\\\/ocs\\\/v1.php(77): OC\\\\Route\\\\Router->match('\\\/ocsapp\\\/apps\\\/sp...')\\n#9 \\\/srv\\\/www\\\/ocs\\\/v2.php(23): require_once('\\\/srv\\\/www\\\/ocs\\\/v1...')\\n#10 {main}\",\"File\":\"\\\/srv\\\/www\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Request.php\",\"Line\":410}","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/59.0.3071.115 Safari\/537.36","version":"13.0.0.1"}
```

@nickvergessen any suggestions how this should be fixed? Change to a `POST` / send some data / something else?

**Comment by fancycode** [comment]
For reference, this is a sample request:
```
PUT /ocs/v2.php/apps/spreed/api/v1/call/4wum HTTP/1.1
Host: my-nextcloud-host
Connection: keep-alive
Content-Length: 0
Pragma: no-cache
Cache-Control: no-cache
requesttoken: snip:snip
Origin: https://my-nextcloud-host
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36
OCS-APIREQUEST: true
Accept: */*
X-Requested-With: XMLHttpRequest
Accept-Encoding: gzip, deflate, br
Accept-Language: de-DE,de;q=0.8,en-US;q=0.6,en;q=0.4
Cookie: nc_sameSiteCookielax=true; nc_sameSiteCookiestrict=true; oc_sessionPassphrase=snip; snip=snip
DNT: 1

```

**Comment by nickvergessen** [comment]
Post is `im here for a call now, give me the session and signaling server info`
So I guess we just add a dummy body to the PUT?

**Comment by fancycode** [comment]
Or we could do an empty `POST` to `/api/{apiVersion}/call/{token}/ping`. Would make the functionality clear from the URL.
