### ISSUE TITLE
Spreed unable to enable since NC 17

### ISSUE THREAD

**Issue by netzgestaltung** [nextcloud/spreed#4352]
## Steps to reproduce in Webinterface (All text translated from german, i don't know the english interface)
1. Goto Apps, klick on Talk/Enable
2. A message pops up
3. There was en error with the request. It cannot be continued.
4. Removing it completely and reinstalling/downloading makes no difference

## Steps to reproduce on CLI
1. Login to Server, navigate to NC root folder
2. sudo -u www-data php occ app:enable spreed
3. `An unhandled exception has been thrown: json_decode() expects parameter 1 to be string` (more see below)

### Expected behaviour
Talk is enabled and useable

### Actual behaviour
Talk is not enabled.

## Talk app

**Talk app version:** 9.0.4

**Custom Signaling server configured:** no

**Custom TURN server configured:** no

**Custom STUN server configured:** no

## Browser

**Microphone available:** yes

**Camera available:** no

**Operating system:** Fedora 32

**Browser name:** Firefox

**Browser version:** 81.0.1

### Browser log

a) The javascript console log

<details>

```
{…}
​__ob__: Object { value: {…}, dep: {…}, vmCount: 0 }
​apps: 
​oc: 
​route: 
​settings: 
​users: 
​<get apps()>: function get()
​<set apps()>: function set(e)
​<get oc()>: function get()
​<set oc()>: function set(e)
​<get route()>: function get()
​<set route()>: function set(e)
​<get settings()>: function get()
​<set settings()>: function set(e)
​<get users()>: function get()
​<set users()>: function set(e)
​<prototype>: Object { … }
 Object { appId: "spreed", error: TypeError }
index.js:43:10
    API_FAILURE index.js:43
    h vuex.esm.js:744
    commit vuex.esm.js:392
    commit vuex.esm.js:391
    _withCommit vuex.esm.js:526
    commit vuex.esm.js:390
    commit vuex.esm.js:335
    enableApp apps.js:214
    (Async: promise callback)
    enableApp apps.js:214
    h vuex.esm.js:751
    dispatch vuex.esm.js:442
    dispatch vuex.esm.js:332
    enable AppManagement.vue:112
    click AppItem.vue:1
    VueJS 3
        Gt
        n
        _wrapper

```

</details>

b) The network log -> no idea how to get

c) CLI Log

<details>

```
sudo -u www-data php occ app:enable spreed
An unhandled exception has been thrown:
TypeError: json_decode() expects parameter 1 to be string, null given in /apps/spreed/lib/Migration/Version2001Date20171026134605.php:391
Stack trace:
#0 /apps/spreed/lib/Migration/Version2001Date20171026134605.php(391): json_decode()
#1 /apps/spreed/lib/Migration/Version2001Date20171026134605.php(171): OCA\Talk\Migration\Version2001Date20171026134605->fixActivityMails()
#2 /lib/private/DB/MigrationService.php(493): OCA\Talk\Migration\Version2001Date20171026134605->postSchemaChange()
#3 /lib/private/DB/MigrationService.php(414): OC\DB\MigrationService->executeStep()
#4 /lib/private/Installer.php(157): OC\DB\MigrationService->migrate()
#5 /core/Command/App/Enable.php(122): OC\Installer->installApp()
#6 /core/Command/App/Enable.php(92): OC\Core\Command\App\Enable->enableApp()
#7 /3rdparty/symfony/console/Command/Command.php(255): OC\Core\Command\App\Enable->execute()
#8 /3rdparty/symfony/console/Application.php(1012): Symfony\Component\Console\Command\Command->run()
#9 /3rdparty/symfony/console/Application.php(272): Symfony\Component\Console\Application->doRunCommand()
#10 /3rdparty/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun()
#11 /lib/private/Console/Application.php(215): Symfony\Component\Console\Application->run()
#12 /console.php(100): OC\Console\Application->run()
#13 /occ(11): require_once('/private/path_to_root...')

```

</details>

## Server configuration

**Operating system**: Debian 10

**Web server:** Apache

**Database:** MySQL

**PHP version:** 7.4

**Nextcloud Version:** 19.0.4

**List of activated apps:**

<details>

```

sudo -u www-data php occ app:list
Enabled:
  - accessibility: 1.5.0
  - activity: 2.12.1
  - audioplayer: 2.12.0
  - calendar: 2.0.4
  - cloud_federation_api: 1.2.0
  - comments: 1.9.0
  - contacts: 3.4.0
  - contactsinteraction: 1.0.0
  - dav: 1.15.0
  - documentserver_community: 0.1.8
  - federatedfilesharing: 1.9.0
  - federation: 1.9.0
  - files: 1.14.0
  - files_external: 1.10.0
  - files_markdown: 2.3.1
  - files_pdfviewer: 1.8.0
  - files_rightclick: 0.16.0
  - files_sharing: 1.11.0
  - files_trashbin: 1.9.0
  - files_versions: 1.12.0
  - files_videoplayer: 1.8.0
  - firstrunwizard: 2.8.0
  - logreader: 2.4.0
  - lookup_server_connector: 1.7.0
  - mail: 1.4.1
  - maps: 0.1.6
  - metadata: 0.12.0
  - music: 0.16.0
  - nextcloud_announcements: 1.8.0
  - notifications: 2.7.0
  - oauth2: 1.7.0
  - ocsms: 2.1.8
  - ojsxc: 4.1.1
  - onlyoffice: 6.0.2
  - password_policy: 1.9.1
  - passwords: 2020.10.0
  - photos: 1.1.0
  - privacy: 1.3.0
  - provisioning_api: 1.9.0
  - recommendations: 0.7.0
  - serverinfo: 1.9.0
  - settings: 1.1.0
  - sharebymail: 1.9.0
  - support: 1.2.1
  - survey_client: 1.7.0
  - systemtags: 1.9.0
  - text: 3.0.1
  - theming: 1.10.0
  - twofactor_backupcodes: 1.8.0
  - updatenotification: 1.9.0
  - viewer: 1.3.0
  - workflowengine: 2.1.0
Disabled:
  - admin_audit
  - apporder
  - bruteforcesettings
  - deck
  - encryption
  - files_downloadactivity
  - files_readmemd
  - spreed
  - tasks
  - user_ldap

```

</details>

**Nextcloud configuration:**

<details>

```

sudo -u www-data php occ config:list system
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "19.0.4.2",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "maintenance": false,
        "theme": "",
        "loglevel": 0,
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "ssl",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "updater.secret": "***REMOVED SENSITIVE VALUE***",
        "trashbin_retention_obligation": "3, auto",
        "updater.release.channel": "stable",
        "app_install_overwrite": [
            "mail",
            "ojsxc"
        ],
        "mysql.utf8mb4": true
    }
}

```

</details>

### Server log (data/nextcloud.log)

<details>

```

tail -n 10 data/nextcloud.log 
{"reqId":"4UU4wjCkQMkaFaCUUf7h","level":3,"time":"2020-10-11T07:36:35+00:00","remoteAddr":"10.25.10.40","user":"<username>","app":"no app in context","method":"POST","url":"/index.php/settings/apps/enable","message":{"Exception":"Symfony\\Component\\Routing\\Exception\\RouteNotFoundException","Message":"Unable to generate a URL for the named route \"spreed.Page.index\" as such route does not exist.","Code":0,"Trace":[{"file":"/lib/private/Route/Router.php","line":338,"function":"generate","class":"Symfony\\Component\\Routing\\Generator\\UrlGenerator","type":"->"},{"file":"/lib/private/Route/CachingRouter.php","line":60,"function":"generate","class":"OC\\Route\\Router","type":"->"},{"file":"/lib/private/URLGenerator.php","line":83,"function":"generate","class":"OC\\Route\\CachingRouter","type":"->"},{"file":"/lib/private/URLGenerator.php","line":95,"function":"linkToRoute","class":"OC\\URLGenerator","type":"->"},{"file":"/apps/spreed/lib/AppInfo/Application.php","line":148,"function":"linkToRouteAbsolute","class":"OC\\URLGenerator","type":"->"},{"file":"/lib/private/NavigationManager.php","line":117,"function":"OCA\\Talk\\AppInfo\\{closure}","class":"OCA\\Talk\\AppInfo\\Application","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/apps/theming/lib/ThemingDefaults.php","line":183,"function":"getAll","class":"OC\\NavigationManager","type":"->"},{"file":"/lib/private/legacy/OC_Defaults.php","line":263,"function":"getShortFooter","class":"OCA\\Theming\\ThemingDefaults","type":"->"},{"file":"/lib/public/Defaults.php","line":169,"function":"getLongFooter","class":"OC_Defaults","type":"->"},{"file":"/core/templates/layout.guest.php","line":55,"function":"getLongFooter","class":"OCP\\Defaults","type":"->"},{"file":"/lib/private/Template/Base.php","line":178,"args":["/core/templates/layout.guest.php"],"function":"include"},{"file":"/lib/private/Template/Base.php","line":150,"function":"load","class":"OC\\Template\\Base","type":"->"},{"file":"/lib/private/legacy/OC_Template.php","line":182,"function":"fetchPage","class":"OC\\Template\\Base","type":"->"},{"file":"/lib/private/legacy/OC_Template.php","line":213,"function":"fetchPage","class":"OC_Template","type":"->"},{"file":"/lib/private/Template/Base.php","line":132,"function":"fetchPage","class":"OC_Template","type":"->"},{"file":"/lib/private/legacy/OC_Template.php","line":334,"function":"printPage","class":"OC\\Template\\Base","type":"->"},{"file":"/index.php","line":63,"function":"printExceptionErrorPage","class":"OC_Template","type":"::"}],"File":"/3rdparty/symfony/routing/Generator/UrlGenerator.php","Line":143,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:81.0) Gecko/20100101 Firefox/81.0","version":"19.0.4.2"}
{"reqId":"My4n0kgZLKUqstUdo2Mm","level":0,"time":"2020-10-11T07:38:58+00:00","remoteAddr":"80.110.110.178","user":"--","app":"caldav","method":"OPTIONS","url":"/remote.php/caldav/calendars/sunshine/contact_birthdays/","message":{"Exception":"Sabre\\DAV\\Exception\\NotAuthenticated","Message":"No 'Authorization: Basic' header found. Either the client didn't send one, or the server is misconfigured","Code":0,"Trace":[{"file":"/3rdparty/sabre/event/lib/WildcardEmitterTrait.php","line":89,"function":"beforeMethod","class":"Sabre\\DAV\\Auth\\Plugin","type":"->"},{"file":"/3rdparty/sabre/dav/lib/DAV/Server.php","line":458,"function":"emit","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/3rdparty/sabre/dav/lib/DAV/Server.php","line":251,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/3rdparty/sabre/dav/lib/DAV/Server.php","line":319,"function":"start","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/apps/dav/appinfo/v1/caldav.php","line":104,"function":"exec","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/remote.php","line":167,"args":["/apps/dav/appinfo/v1/caldav.php"],"function":"require_once"}],"File":"/3rdparty/sabre/dav/lib/DAV/Auth/Plugin.php","Line":161,"CustomMessage":"--"},"userAgent":"Evolution/3.28.5","version":"19.0.4.2"}
{"reqId":"Jqjl8mt0om3dThPDvEVY","level":0,"time":"2020-10-11T07:38:58+00:00","remoteAddr":"80.110.110.178","user":"--","app":"caldav","method":"OPTIONS","url":"/remote.php/caldav/calendars/sunshine/personal/","message":{"Exception":"Sabre\\DAV\\Exception\\NotAuthenticated","Message":"No 'Authorization: Basic' header found. Either the client didn't send one, or the server is misconfigured","Code":0,"Trace":[{"file":"/3rdparty/sabre/event/lib/WildcardEmitterTrait.php","line":89,"function":"beforeMethod","class":"Sabre\\DAV\\Auth\\Plugin","type":"->"},{"file":"/3rdparty/sabre/dav/lib/DAV/Server.php","line":458,"function":"emit","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/3rdparty/sabre/dav/lib/DAV/Server.php","line":251,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/3rdparty/sabre/dav/lib/DAV/Server.php","line":319,"function":"start","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/apps/dav/appinfo/v1/caldav.php","line":104,"function":"exec","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/remote.php","line":167,"args":["/apps/dav/appinfo/v1/caldav.php"],"function":"require_once"}],"File":"/3rdparty/sabre/dav/lib/DAV/Auth/Plugin.php","Line":161,"CustomMessage":"--"},"userAgent":"Evolution/3.28.5","version":"19.0.4.2"}
{"reqId":"gL1A7dLA42oltWyjC12V","level":0,"time":"2020-10-11T07:40:07+00:00","remoteAddr":"10.25.10.40","user":"<username>","app":"no app in context","method":"POST","url":"/index.php/settings/apps/enable","message":"Deprecated event type for \\OC\\Repair::step: Symfony\\Component\\EventDispatcher\\GenericEvent","userAgent":"Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:81.0) Gecko/20100101 Firefox/81.0","version":"19.0.4.2"}
{"reqId":"gL1A7dLA42oltWyjC12V","level":3,"time":"2020-10-11T07:40:09+00:00","remoteAddr":"10.25.10.40","user":"<username>","app":"PHP","method":"POST","url":"/index.php/settings/apps/enable","message":{"Exception":"Error","Message":"Undefined index: subjectparams at /apps/spreed/lib/Migration/Version2001Date20171026134605.php#391","Code":0,"Trace":[{"file":"/apps/spreed/lib/Migration/Version2001Date20171026134605.php","line":391,"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::"},{"file":"/apps/spreed/lib/Migration/Version2001Date20171026134605.php","line":171,"function":"fixActivityMails","class":"OCA\\Talk\\Migration\\Version2001Date20171026134605","type":"->"},{"file":"/lib/private/DB/MigrationService.php","line":493,"function":"postSchemaChange","class":"OCA\\Talk\\Migration\\Version2001Date20171026134605","type":"->"},{"file":"/lib/private/DB/MigrationService.php","line":414,"function":"executeStep","class":"OC\\DB\\MigrationService","type":"->"},{"file":"/lib/private/Installer.php","line":157,"function":"migrate","class":"OC\\DB\\MigrationService","type":"->"},{"file":"/apps/settings/lib/Controller/AppSettingsController.php","line":447,"function":"installApp","class":"OC\\Installer","type":"->"},{"file":"/lib/private/AppFramework/Http/Dispatcher.php","line":170,"function":"enableApps","class":"OCA\\Settings\\Controller\\AppSettingsController","type":"->"},{"file":"/lib/private/AppFramework/Http/Dispatcher.php","line":100,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/lib/private/AppFramework/App.php","line":137,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/lib/private/AppFramework/Routing/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->"},{"file":"/lib/private/Route/Router.php","line":297,"function":"call_user_func"},{"file":"/lib/base.php","line":1011,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/index.php","line":37,"function":"handleRequest","class":"OC","type":"::"}],"File":"/lib/private/Log/ErrorHandler.php","Line":91,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:81.0) Gecko/20100101 Firefox/81.0","version":"19.0.4.2"}
{"reqId":"gL1A7dLA42oltWyjC12V","level":3,"time":"2020-10-11T07:40:09+00:00","remoteAddr":"10.25.10.40","user":"<username>","app":"index","method":"POST","url":"/index.php/settings/apps/enable","message":{"Exception":"Exception","Message":"json_decode() expects parameter 1 to be string, null given","Code":0,"Trace":[{"file":"/lib/private/AppFramework/App.php","line":137,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/lib/private/AppFramework/Routing/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->"},{"file":"/lib/private/Route/Router.php","line":297,"function":"call_user_func"},{"file":"/lib/base.php","line":1011,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/index.php","line":37,"function":"handleRequest","class":"OC","type":"::"}],"File":"/lib/private/AppFramework/Http/Dispatcher.php","Line":110,"Previous":{"Exception":"TypeError","Message":"json_decode() expects parameter 1 to be string, null given","Code":0,"Trace":[{"file":"/apps/spreed/lib/Migration/Version2001Date20171026134605.php","line":391,"function":"json_decode"},{"file":"/apps/spreed/lib/Migration/Version2001Date20171026134605.php","line":171,"function":"fixActivityMails","class":"OCA\\Talk\\Migration\\Version2001Date20171026134605","type":"->"},{"file":"/lib/private/DB/MigrationService.php","line":493,"function":"postSchemaChange","class":"OCA\\Talk\\Migration\\Version2001Date20171026134605","type":"->"},{"file":"/lib/private/DB/MigrationService.php","line":414,"function":"executeStep","class":"OC\\DB\\MigrationService","type":"->"},{"file":"/lib/private/Installer.php","line":157,"function":"migrate","class":"OC\\DB\\MigrationService","type":"->"},{"file":"/apps/settings/lib/Controller/AppSettingsController.php","line":447,"function":"installApp","class":"OC\\Installer","type":"->"},{"file":"/lib/private/AppFramework/Http/Dispatcher.php","line":170,"function":"enableApps","class":"OCA\\Settings\\Controller\\AppSettingsController","type":"->"},{"file":"/lib/private/AppFramework/Http/Dispatcher.php","line":100,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/lib/private/AppFramework/App.php","line":137,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/lib/private/AppFramework/Routing/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->"},{"file":"/lib/private/Route/Router.php","line":297,"function":"call_user_func"},{"file":"/lib/base.php","line":1011,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/index.php","line":37,"function":"handleRequest","class":"OC","type":"::"}],"File":"/apps/spreed/lib/Migration/Version2001Date20171026134605.php","Line":391},"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:81.0) Gecko/20100101 Firefox/81.0","version":"19.0.4.2"}
{"reqId":"gL1A7dLA42oltWyjC12V","level":3,"time":"2020-10-11T07:40:09+00:00","remoteAddr":"10.25.10.40","user":"<username>","app":"no app in context","method":"POST","url":"/index.php/settings/apps/enable","message":{"Exception":"Symfony\\Component\\Routing\\Exception\\RouteNotFoundException","Message":"Unable to generate a URL for the named route \"spreed.Page.index\" as such route does not exist.","Code":0,"Trace":[{"file":"/lib/private/Route/Router.php","line":338,"function":"generate","class":"Symfony\\Component\\Routing\\Generator\\UrlGenerator","type":"->"},{"file":"/lib/private/Route/CachingRouter.php","line":60,"function":"generate","class":"OC\\Route\\Router","type":"->"},{"file":"/lib/private/URLGenerator.php","line":83,"function":"generate","class":"OC\\Route\\CachingRouter","type":"->"},{"file":"/lib/private/URLGenerator.php","line":95,"function":"linkToRoute","class":"OC\\URLGenerator","type":"->"},{"file":"/apps/spreed/lib/AppInfo/Application.php","line":148,"function":"linkToRouteAbsolute","class":"OC\\URLGenerator","type":"->"},{"file":"/lib/private/NavigationManager.php","line":117,"function":"OCA\\Talk\\AppInfo\\{closure}","class":"OCA\\Talk\\AppInfo\\Application","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/apps/theming/lib/ThemingDefaults.php","line":183,"function":"getAll","class":"OC\\NavigationManager","type":"->"},{"file":"/lib/private/legacy/OC_Defaults.php","line":263,"function":"getShortFooter","class":"OCA\\Theming\\ThemingDefaults","type":"->"},{"file":"/lib/public/Defaults.php","line":169,"function":"getLongFooter","class":"OC_Defaults","type":"->"},{"file":"/core/templates/layout.guest.php","line":55,"function":"getLongFooter","class":"OCP\\Defaults","type":"->"},{"file":"/lib/private/Template/Base.php","line":178,"args":["/core/templates/layout.guest.php"],"function":"include"},{"file":"/lib/private/Template/Base.php","line":150,"function":"load","class":"OC\\Template\\Base","type":"->"},{"file":"/lib/private/legacy/OC_Template.php","line":182,"function":"fetchPage","class":"OC\\Template\\Base","type":"->"},{"file":"/lib/private/legacy/OC_Template.php","line":213,"function":"fetchPage","class":"OC_Template","type":"->"},{"file":"/lib/private/Template/Base.php","line":132,"function":"fetchPage","class":"OC_Template","type":"->"},{"file":"/lib/private/legacy/OC_Template.php","line":334,"function":"printPage","class":"OC\\Template\\Base","type":"->"},{"file":"/index.php","line":63,"function":"printExceptionErrorPage","class":"OC_Template","type":"::"}],"File":"/3rdparty/symfony/routing/Generator/UrlGenerator.php","Line":143,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:81.0) Gecko/20100101 Firefox/81.0","version":"19.0.4.2"}
{"reqId":"xvyUZe3haRlyE7O9R0Tb","level":1,"time":"2020-10-11T07:44:16+00:00","remoteAddr":"","user":"--","app":"cli","method":"","url":"--","message":"Memcache \\OC\\Memcache\\APCu not available for local cache","userAgent":"--","version":"19.0.4.2"}
{"reqId":"xvyUZe3haRlyE7O9R0Tb","level":1,"time":"2020-10-11T07:44:16+00:00","remoteAddr":"","user":"--","app":"cli","method":"","url":"--","message":"Memcache \\OC\\Memcache\\APCu not available for distributed cache","userAgent":"--","version":"19.0.4.2"}
{"reqId":"xvyUZe3haRlyE7O9R0Tb","level":1,"time":"2020-10-11T07:44:16+00:00","remoteAddr":"","user":"--","app":"passwords","method":"","url":"--","message":"Passwords runs occ in global mode","userAgent":"--","version":"19.0.4.2"}

```

</details>

Hi, since version 17 of nextcloud at one of my instances i cant reenable talk, no matter what version i had since then. I have no idea whats wrong with it.

Please help.

Thank you for your effort.

Br,
tom

**Comment by acsfer** [comment]
Is this related to Talk app only? If not, it can be related to https://github.com/nextcloud/server/issues/23334

**Comment by nickvergessen** [comment]
Hmm, it seems to be an issue with your activity app not being up to date. Can you post the table structure of `oc_activities`

**Comment by netzgestaltung** [comment]
Hi,

i assume you got a type here, i only have the tables oc_activity and oc_activity_mq

This is the structure of oc_activity:

```
MariaDB [mydb]> DESCRIBE oc_activity;
+---------------+---------------+------+-----+---------+----------------+
| Field         | Type          | Null | Key | Default | Extra          |
+---------------+---------------+------+-----+---------+----------------+
| activity_id   | bigint(20)    | NO   | PRI | NULL    | auto_increment |
| timestamp     | int(11)       | NO   |     | 0       |                |
| priority      | int(11)       | NO   |     | 0       |                |
| type          | varchar(255)  | YES  |     | NULL    |                |
| user          | varchar(64)   | YES  |     | NULL    |                |
| affecteduser  | varchar(64)   | NO   | MUL | NULL    |                |
| app           | varchar(32)   | NO   |     | NULL    |                |
| subject       | varchar(255)  | NO   |     | NULL    |                |
| subjectparams | longtext      | NO   |     | NULL    |                |
| message       | varchar(255)  | YES  |     | NULL    |                |
| messageparams | longtext      | YES  |     | NULL    |                |
| file          | varchar(4000) | YES  |     | NULL    |                |
| link          | varchar(4000) | YES  |     | NULL    |                |
| object_type   | varchar(255)  | YES  | MUL | NULL    |                |
| object_id     | bigint(20)    | NO   |     | 0       |                |
+---------------+---------------+------+-----+---------+----------------+
15 rows in set (0.001 sec)

```

**Comment by nickvergessen** [comment]
But here the column `subjectparams` exists, so why would it fail to get that :thinking:

**Comment by netzgestaltung** [comment]
i don't know, maybe its missing in another table?

do you think its related to the problem or another thing?

**Comment by netzgestaltung** [comment]
Hi,

to get a solution i thought about that:

# remove Talk app from system (uninstall)
# delete all related tables in MariaDB `oc_spreedme_room_participants`, `oc_spreedme_rooms`, `oc_talk_participants`, `oc_talk_rooms`, `oc_talk_signaling`
# reinstall Talk app

is this possible without breaking NC entirely? Should i instead only remove the contents of that tables?

**Comment by nickvergessen** [comment]
https://github.com/nextcloud/spreed/issues/772#issuecomment-384211357

**Comment by netzgestaltung** [comment]
Deleting all realted data and tables worked, now i was able to install talk:

> warning Use at own risk, this **really** whips all data, rooms, chats, activities, notifications, ... warning
> warning This was written for SpreedMe and Talk up to version 3.1 warning
> ### Clean tables of server and apps:
> 
> ```sql
> DELETE FROM `oc_activity` WHERE `app` = 'spreed';
> DELETE FROM `oc_activity_mq` WHERE `amq_appid` = 'spreed';
> DELETE FROM `oc_appconfig` WHERE `appid` = 'spreed';
> DELETE FROM `oc_comments` WHERE `object_type` = 'chat';
> DELETE FROM `oc_comments_read_markers` WHERE `object_type` = 'chat';
> DELETE FROM `oc_filecache` WHERE `path` LIKE '%spreed%';
> DELETE FROM `oc_jobs` WHERE `class` LIKE '%Spreed%';
> DELETE FROM `oc_migrations` WHERE `app` = 'spreed';
> DELETE FROM `oc_notifications` WHERE `app` = 'spreed';
> DELETE FROM `oc_preferences` WHERE `appid` = 'spreed';
> ```
> 
> ### Delete former tables
> 
> ```sql
> DROP TABLE `oc_spreedme_messages`;
> DROP TABLE `oc_spreedme_rooms`;
> DROP TABLE `oc_spreedme_room_participants`;
> DROP TABLE `oc_videocalls_signaling`;
> ```
> 
> ### Delete current tables
> 
> ```sql
> DROP TABLE `oc_talk_guests`;
> DROP TABLE `oc_talk_participants`;
> DROP TABLE `oc_talk_rooms`;
> DROP TABLE `oc_talk_signaling`;
> ```
> 
> ### Delete cached css files
> 
> Inside your data directory there is a `appdata_oc*random string*` directory. Navigate into that and run the following command:
> 
> ```shell
> rm -rf css/spreed/
> ```
> 
> ### Delete the app files
> 
> In your Nextcloud root (not data directory root, in case you use a non default app-dir adjust the path):
> 
> ```shell
> rm -rf apps/spreed/
> ```

some steps produced errors when the data was not there, but then that was the proove.
