### ISSUE TITLE
Talk app fails repair step for NC 21-beta

### ISSUE THREAD

**Issue by tcitworld** [nextcloud/spreed#4752]
Will investigate later to see where the wiring is broken between `Psr\Log\LoggerInterface` and `instance of OC\AppFramework\Logger`.

```
TypeError: Argument 2 passed to OC\Comments\Manager::__construct() must implement interface Psr\Log\LoggerInterface, instance of OC\AppFramework\Logger given, called in /var/www/nextcloud/apps/spreed/lib/Chat/CommentsManager.php on line 46 and defined in /var/www/nextcloud/lib/private/Comments/Manager.php:77
Stack trace:                                                                                                                                                                            #0 /var/www/nextcloud/apps/spreed/lib/Chat/CommentsManager.php(46): OC\Comments\Manager->__construct(Object(OC\DB\Connection), Object(OC\AppFramework\Logger), Object(OC\AllConfig))
#1 [internal function]: OCA\Talk\Chat\CommentsManager->__construct(Object(OC\DB\Connection), Object(OC\AppFramework\Logger), Object(OC\AllConfig), Object(OC\AppFramework\Utility\TimeFactory))                       
#2 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(101): ReflectionClass->newInstanceArgs(Array)
#3 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(109): OC\AppFramework\Utility\SimpleContainer->buildClass(Object(ReflectionClass))
#4 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(126): OC\AppFramework\Utility\SimpleContainer->resolve('OCA\\Talk\\Chat\\C...')
#5 /var/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php(459): OC\AppFramework\Utility\SimpleContainer->query('OCA\\Talk\\Chat\\C...')
#6 /var/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php(431): OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback('OCA\\Talk\\Chat\\C...')
#7 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(87): OC\AppFramework\DependencyInjection\DIContainer->query('OCA\\Talk\\Chat\\C...', true)
#8 [internal function]: OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}(Object(ReflectionParameter))
#9 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(101): array_map(Object(Closure), Array)
#10 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(109): OC\AppFramework\Utility\SimpleContainer->buildClass(Object(ReflectionClass))
#11 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(126): OC\AppFramework\Utility\SimpleContainer->resolve('OCA\\Talk\\Manage...')
#12 /var/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php(459): OC\AppFramework\Utility\SimpleContainer->query('OCA\\Talk\\Manage...')
#13 /var/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php(431): OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback('OCA\\Talk\\Manage...')
#14 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(87): OC\AppFramework\DependencyInjection\DIContainer->query('OCA\\Talk\\Manage...', true)
#15 [internal function]: OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}(Object(ReflectionParameter))
#16 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(101): array_map(Object(Closure), Array)
#17 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(109): OC\AppFramework\Utility\SimpleContainer->buildClass(Object(ReflectionClass))
#18 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(126): OC\AppFramework\Utility\SimpleContainer->resolve('OCA\\Talk\\Collab...')
#19 /var/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php(459): OC\AppFramework\Utility\SimpleContainer->query('OCA\\Talk\\Collab...')
#20 /var/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php(431): OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback('OCA\\Talk\\Collab...')
#21 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(87): OC\AppFramework\DependencyInjection\DIContainer->query('OCA\\Talk\\Collab...', true)
#22 [internal function]: OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}(Object(ReflectionParameter))
#23 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(101): array_map(Object(Closure), Array)
#24 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(109): OC\AppFramework\Utility\SimpleContainer->buildClass(Object(ReflectionClass))
#25 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(126): OC\AppFramework\Utility\SimpleContainer->resolve('OCA\\Talk\\Migrat...')
#26 /var/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php(459): OC\AppFramework\Utility\SimpleContainer->query('OCA\\Talk\\Migrat...')
#27 /var/www/nextcloud/lib/private/ServerContainer.php(146): OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback('OCA\\Talk\\Migrat...')
#28 /var/www/nextcloud/lib/private/Repair.php(127): OC\ServerContainer->query('OCA\\Talk\\Migrat...')
#29 /var/www/nextcloud/lib/private/legacy/OC_App.php(1047): OC\Repair->addStep('OCA\\Talk\\Migrat...')
#30 /var/www/nextcloud/lib/private/Installer.php(164): OC_App::executeRepairSteps('spreed', Array)
#31 /var/www/nextcloud/lib/private/legacy/OC_App.php(431): OC\Installer->installApp('spreed')
#32 /var/www/nextcloud/lib/private/Updater.php(421): OC_App->enable('spreed')
#33 /var/www/nextcloud/lib/private/Updater.php(266): OC\Updater->upgradeAppStoreApps(Array, true)
#34 /var/www/nextcloud/lib/private/Updater.php(130): OC\Updater->doUpgrade('21.0.0.8', '20.0.3.2')
#35 /var/www/nextcloud/core/Command/Upgrade.php(255): OC\Updater->upgrade()
#36 /var/www/nextcloud/apps/mail/vendor/symfony/console/Command/Command.php(258): OC\Core\Command\Upgrade->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Com
ponent\Console\Output\ConsoleOutput))
#37 /var/www/nextcloud/apps/mail/vendor/symfony/console/Application.php(920): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(S
ymfony\Component\Console\Output\ConsoleOutput))
#38 /var/www/nextcloud/apps/mail/vendor/symfony/console/Application.php(266): Symfony\Component\Console\Application->doRunCommand(Object(OC\Core\Command\Upgrade), Object(Symfony\Compon
ent\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#39 /var/www/nextcloud/apps/mail/vendor/symfony/console/Application.php(142): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Sym
fony\Component\Console\Output\ConsoleOutput))
#40 /var/www/nextcloud/lib/private/Console/Application.php(215): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\
Console\Output\ConsoleOutput))
#41 /var/www/nextcloud/console.php(100): OC\Console\Application->run()
#42 /var/www/nextcloud/occ(11): require_once('/var/www/nextcl...')
#43 {main}
```

**Comment by tcitworld** [comment]
Oh yeah, I must have had allowed Talk to run on  unsupported versions, sorry about that.

**Comment by nickvergessen** [comment]
Hmm, maybe that "exception" should be per major version 🤔 
Mind to raise an issue in server?

**Comment by rubo77** [comment]
I got the same error on upgrading                                                                                                                                                                                 from 20.0.8.1 to 21.0.0.18 

is there a workaround?

**Comment by nickvergessen** [comment]
Just reenable the app again after the upgrade. There is nothing we can do about this.

**Comment by rubo77** [comment]
@nickvergessen OK, thx.

I had a problem to release the maintenance mode though: 

    docker exec --user www-data nextcloud_app_1 php occ maintenance:mode --off   
This didn't disable maintenance. I had edit the line in `config.php` manually to leave maintenance. after that, I could continue the upgrade in the webinterface... which resulted in the en in a message "an error occured... please reload the page" (or so, I had german locale)

pressing reload in the browser worked and i could log in again and then I could enable the disabled Talk app in settings.

**Comment by flavienbwk** [comment]
Running the following commands made it work for me :

```bash
docker exec --user www-data nextcloud_app_1 php occ maintenance:mode --off   
docker exec --user www-data nextcloud_app_1 php occ upgrade
```
