### ISSUE TITLE
Cannot build Talk on Debian 11

### ISSUE THREAD

**Issue by StCyr** [nextcloud/spreed#6867]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. make dev-setup
2. make build-js

### Expected behaviour
Code buils properly

### Actual behaviour

```
root@vm-cyrille-debian:/var/www/nextcloud23-dev/apps/spreed# make build-js
npm run dev

> talk@14.0.0 dev /var/www/nextcloud23-dev/apps/spreed
> NODE_ENV=development webpack --config webpack.js

internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module 'resolve-cwd'
Require stack:
- /usr/share/nodejs/webpack/node_modules/import-local/index.js
- /usr/share/nodejs/webpack/node_modules/webpack-cli/bin/cli.js
- /usr/share/nodejs/webpack/bin/webpack.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.<anonymous> (/usr/share/nodejs/webpack/node_modules/import-local/index.js:3:20)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/share/nodejs/webpack/node_modules/import-local/index.js',
    '/usr/share/nodejs/webpack/node_modules/webpack-cli/bin/cli.js',
    '/usr/share/nodejs/webpack/bin/webpack.js'
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! talk@14.0.0 dev: `NODE_ENV=development webpack --config webpack.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the talk@14.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-02-05T18_02_48_835Z-debug.log
make: *** [Makefile:23: build-js] Error 1
root@vm-cyrille-debian:/var/www/nextcloud23-dev/apps/spreed#
```

## Build environnement details

* Debian 11
* npm 6.14.16
* nodejs v14.19.0

```
root@vm-cyrille-debian:/var/www/nextcloud23-dev/apps/spreed# apt search resolve-cwd
Sorting... Done
Full Text Search... Done
node-resolve-cwd/stable,stable,oldstable,now 2.0.0-2 all [installed,automatic]
  Resolve the path of a module from current directory
```

**Comment by nickvergessen** [comment]
You need node 14 and npm 7
It's the same in basically all Nextcloud apps

**Comment by StCyr** [comment]
ok, I've succeeded in installing your requirements and Talk builds properly
