### ISSUE TITLE
Failing to add reaction to a message

### ISSUE THREAD

**Issue by meldarionqeusse** [nextcloud/spreed#7334]
## Steps to reproduce
try to add a reaction to a message and got this error
![image](https://user-images.githubusercontent.com/21668964/167121403-40bfa27d-a990-405e-9b56-fb7fd45748f9.png)

### Expected behaviour
Reaction added to message

### Actual behaviour
Got an error saying Failed to add reaction

## Talk app: 14.0 

**Custom Signaling server configured:** No

**Custom TURN server configured:** NO

**Custom STUN server configured:** No

## Browser
**Microphone available:** yes

**Camera available:** yes

**Operating system:** Windows

**Browser name:** Chrome

**Browser version:** 100

### Browser log

<details>
```
Insert your browser log here, this could for example include:
xhr.js:210          POST https://mydomain.com/nextcloud/ocs/v2.php/apps/spreed/api/v1/reaction/ok56zf6v/91 500 (Internal Server Error)
(anonymous) @ xhr.js:210
e.exports @ xhr.js:15
e.exports @ dispatchRequest.js:56
c.request @ Axios.js:112
a.forEach.c.<computed> @ Axios.js:147
(anonymous) @ bind.js:9
(anonymous) @ messagesService.js:136
c @ runtime.js:63
(anonymous) @ runtime.js:294
(anonymous) @ runtime.js:119
ae @ guestNameStore.js:101
o @ guestNameStore.js:101
(anonymous) @ guestNameStore.js:101
(anonymous) @ guestNameStore.js:101
(anonymous) @ messagesService.js:135
(anonymous) @ messagesStore.js:1009
c @ runtime.js:63
(anonymous) @ runtime.js:294
(anonymous) @ runtime.js:119
ge @ messagesService.js:149
o @ messagesService.js:149
(anonymous) @ messagesService.js:149
(anonymous) @ messagesService.js:149
addReactionToMessage @ messagesStore.js:1001
(anonymous) @ vuex.esm.js:851
h.dispatch @ vuex.esm.js:516
dispatch @ vuex.esm.js:406
handleReactionClick @ MessageButtonsBar.vue:415
click @ MessageButtonsBar.vue?vue&type=template&id=664619c2&scoped=true&:1
qe @ vue.runtime.esm.js:1863
n @ vue.runtime.esm.js:2188
qe @ vue.runtime.esm.js:1863
n @ vue.runtime.esm.js:2184
Sa.r._wrapper @ vue.runtime.esm.js:6961
Show 4 more frames
messagesStore.js:1024 Error: Request failed with status code 500
    at e.exports (createError.js:16:15)
    at e.exports (settle.js:17:12)
    at XMLHttpRequest.C (xhr.js:66:7)
(anonymous) @ messagesStore.js:1024
c @ runtime.js:63
(anonymous) @ runtime.js:294
(anonymous) @ runtime.js:119
ge @ messagesService.js:149
s @ messagesService.js:149
Promise.then (async)
ge @ messagesService.js:149
o @ messagesService.js:149
(anonymous) @ messagesService.js:149
(anonymous) @ messagesService.js:149
addReactionToMessage @ messagesStore.js:1001
(anonymous) @ vuex.esm.js:851
h.dispatch @ vuex.esm.js:516
dispatch @ vuex.esm.js:406
handleReactionClick @ MessageButtonsBar.vue:415
click @ MessageButtonsBar.vue?vue&type=template&id=664619c2&scoped=true&:1
qe @ vue.runtime.esm.js:1863
n @ vue.runtime.esm.js:2188
qe @ vue.runtime.esm.js:1863
n @ vue.runtime.esm.js:2184
Sa.r._wrapper @ vue.runtime.esm.js:6961
```

</details>

## Server configuration

**Operating system**: Raspberry Pi OS 11

**Web server:** Apache/

**Database:** MySQL/Maria

**PHP version:** 8.0/

**Nextcloud Version:** 24

**App List**
<details>

```

Enabled:
  - accessibility: 1.10.0
  - activity: 2.16.0
  - bruteforcesettings: 2.4.0
  - calendar: 3.3.0
  - circles: 24.0.0
  - cloud_federation_api: 1.7.0
  - comments: 1.14.0
  - contacts: 4.1.0
  - contactsinteraction: 1.5.0
  - cookbook: 0.9.11
  - dashboard: 7.4.0
  - dav: 1.22.0
  - federatedfilesharing: 1.14.0
  - federation: 1.14.0
  - files: 1.19.0
  - files_external: 1.16.1
  - files_pdfviewer: 2.5.0
  - files_retention: 1.13.1
  - files_rightclick: 1.3.0
  - files_sharing: 1.16.2
  - files_trashbin: 1.14.0
  - files_versions: 1.17.0
  - files_videoplayer: 1.13.0
  - firstrunwizard: 2.13.0
  - logreader: 2.9.0
  - lookup_server_connector: 1.12.0
  - nextcloud_announcements: 1.13.0
  - notifications: 2.12.0
  - oauth2: 1.12.0
  - password_policy: 1.14.0
  - photos: 1.6.0
  - privacy: 1.8.0
  - provisioning_api: 1.14.0
  - quota_warning: 1.14.0
  - recommendations: 1.3.0
  - richdocuments: 6.0.0
  - richdocumentscode_arm64: 21.11.402
  - serverinfo: 1.14.0
  - settings: 1.6.0
  - sharebymail: 1.14.0
  - spreed: 14.0.0
  - support: 1.7.0
  - survey_client: 1.12.0
  - systemtags: 1.14.0
  - text: 3.5.1
  - theming: 1.15.0
  - twofactor_backupcodes: 1.13.0
  - twofactor_totp: 6.3.0
  - updatenotification: 1.14.0
  - user_status: 1.4.0
  - viewer: 1.8.0
  - weather_status: 1.4.0
  - workflowengine: 2.6.0
Disabled:
  - admin_audit
  - encryption
  - user_ldap

```
</details>

**Nextcloud configuration:**

<details>

```

{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "mydomain.com",
            "192.168.0.xx"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "24.0.0.12",
        "overwrite.cli.url": "https:\/\/mydomain.com\/nextcloud",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "filelocking.enabled": "true",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "timeout": 0
        },
        "maintenance": false,
        "app_install_overwrite": [
            "files_readmemd",
            "cookbook"
        ],
        "updater.secret": "***REMOVED SENSITIVE VALUE***",
        "theme": "",
        "loglevel": 2
    }
}

```
</details>

### Server log (data/nextcloud.log)
<details>

```

{"reqId":"RT6RHcV3cJSvN2OpHlcT","level":2,"time":"2022-02-10T18:12:53+00:00","remoteAddr":"::1","user":"--","app":"no app in context","method":"GET","url":"/nextcloud/","message":"Host localhost was not connected to because it violates local access rules","userAgent":"Mozilla/5.0 (X11; CrOS aarch64 13597.84.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.78 Safari/537.36","version":""}
{"reqId":"RT6RHcV3cJSvN2OpHlcT","level":2,"time":"2022-02-10T18:12:53+00:00","remoteAddr":"::1","user":"--","app":"no app in context","method":"GET","url":"/nextcloud/","message":"Host localhost was not connected to because it violates local access rules","userAgent":"Mozilla/5.0 (X11; CrOS aarch64 13597.84.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.78 Safari/537.36","version":""}
{"reqId":"gh0Tk5xq4hP30isGCpdD","level":2,"time":"2022-02-10T18:15:55+00:00","remoteAddr":"::1","user":"--","app":"no app in context","method":"POST","url":"/nextcloud/index.php","message":"Host localhost was not connected to because it violates local access rules","userAgent":"Mozilla/5.0 (X11; CrOS aarch64 13597.84.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.78 Safari/537.36","version":""}
{"reqId":"gh0Tk5xq4hP30isGCpdD","level":2,"time":"2022-02-10T18:15:55+00:00","remoteAddr":"::1","user":"--","app":"no app in context","method":"POST","url":"/nextcloud/index.php","message":"Host localhost was not connected to because it violates local access rules","userAgent":"Mozilla/5.0 (X11; CrOS aarch64 13597.84.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.78 Safari/537.36","version":""}
{"reqId":"gh0Tk5xq4hP30isGCpdD","level":3,"time":"2022-02-10T18:15:55+00:00","remoteAddr":"::1","user":"--","app":"PHP","method":"POST","url":"/nextcloud/index.php","message":"mkdir(): Permission denied at /var/www/html/nextcloud/lib/private/Setup.php#308","userAgent":"Mozilla/5.0 (X11; CrOS aarch64 13597.84.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.78 Safari/537.36","version":"","exception":{"Exception":"Error","Message":"mkdir(): Permission denied at /var/www/html/nextcloud/lib/private/Setup.php#308","Code":0,"Trace":[{"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::"},{"file":"/var/www/html/nextcloud/lib/private/Setup.php","line":308,"function":"mkdir"},{"file":"/var/www/html/nextcloud/core/Controller/SetupController.php","line":74,"function":"install","class":"OC\\Setup","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/nextcloud/lib/base.php","line":939,"function":"run","class":"OC\\Core\\Controller\\SetupController","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/nextcloud/index.php","line":36,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/html/nextcloud/lib/private/Log/ErrorHandler.php","Line":92,"CustomMessage":"--"}}
{"reqId":"eH2q0xq99XMM9BBIK7Eh","level":2,"time":"2022-02-10T18:17:09+00:00","remoteAddr":"::1","user":"--","app":"no app in context","method":"POST","url":"/nextcloud/index.php","message":"Host localhost was not connected to because it violates local access rules","userAgent":"Mozilla/5.0 (X11; CrOS aarch64 13597.84.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.78 Safari/537.36","version":""}
{"reqId":"eH2q0xq99XMM9BBIK7Eh","level":2,"time":"2022-02-10T18:17:09+00:00","remoteAddr":"::1","user":"--","app":"no app in context","method":"POST","url":"/nextcloud/index.php","message":"Host localhost was not connected to because it violates local access rules","userAgent":"Mozilla/5.0 (X11; CrOS aarch64 13597.84.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.78 Safari/537.36","version":""}
{"reqId":"lt4E3U5T9HGnHvQMlFOo","level":2,"time":"2022-02-10T18:17:42+00:00","remoteAddr":"::1","user":"--","app":"no app in context","method":"POST","url":"/nextcloud/index.php","message":"Host localhost was not connected to because it violates local access rules","userAgent":"Mozilla/5.0 (X11; CrOS aarch64 13597.84.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.78 Safari/537.36","version":""}
{"reqId":"lt4E3U5T9HGnHvQMlFOo","level":2,"time":"2022-02-10T18:17:42+00:00","remoteAddr":"::1","user":"--","app":"no app in context","method":"POST","url":"/nextcloud/index.php","message":"Host localhost was not connected to because it violates local access rules","userAgent":"Mozilla/5.0 (X11; CrOS aarch64 13597.84.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.78 Safari/537.36","version":""}

```
</details>

**Comment by Luticus** [comment]
In my case I notice this seems to happen when trying to react to something that a script posted. I can add reactions to general conversation so far, also to the matterbridge talk bot, but like poll messages or anything posted by a script fails.

**Comment by nickvergessen** [comment]
Commands might not work at the moment, that is right. The issue is that they could be restricted in visibility and then clients get notified about a reaction to a message they don't have.
But this also means we should remove the option to react from such messages.

As for the initial report: Is it also a command for you? Otherwise can you say which reaction you tried? Does it happen for all or only some?

**Comment by nickvergessen** [comment]
I think this is solved now.

At least the option is not shown for commands anymore

**Comment by meldarionqeusse** [comment]
Still the same issue on Nextcloud 25

**Comment by nickvergessen** [comment]
Can you please check whether there is something in your nextcloud.log file then? We react daily hundred times on our company instance and it works totally fine

**Comment by nickvergessen** [comment]
In the browser log it says:
> POST https://mydomain.com/nextcloud/ocs/v2.php/apps/spreed/api/v1/reaction/ok56zf6v/91 500 (Internal Server Error)

So there has to be an entry in nextcloud.log (or if that fails or is not writable or something check the error.log of apache)

**Comment by meldarionqeusse** [comment]
I got this in the browser log. 

>  POST https://mydomain.com/nextcloud/ocs/v2.php/apps/spreed/api/v1/reaction/f2544j7d/114 400 (Bad request)

Do you have an idea what could be causing this? Thanks for taking time to try and help me resolve this issue.

**Comment by BehroozAmoozad** [comment]
Is this solved or nofix?  
I'm still getting a 400 error along with this:  
`
https://nextcloud.mydomain/ocs/v2.php/apps/spreed/api/v1/reaction/5ru2tyjj/639
[HTTP/2 400  45ms]

1
{"ocs":{"meta":{"status":"failure","statuscode":400,"message":""},"data":[]}}

`

**Comment by miaulalala** [comment]
> I got this in the browser log.
> 
> > POST [mydomain.com/nextcloud/ocs/v2.php/apps/spreed/api/v1/reaction/f2544j7d/114](https://mydomain.com/nextcloud/ocs/v2.php/apps/spreed/api/v1/reaction/f2544j7d/114) 400 (Bad request)
> 
> Do you have an idea what could be causing this? Thanks for taking time to try and help me resolve this issue.

can you enable [debug logging](https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/logging_configuration.html) on your instance so we can have a look at the stack trace? 🙏

**Comment by miaulalala** [comment]
> Is this solved or nofix? I'm still getting a 400 error along with this:
> 
> ```
> https://nextcloud.mydomain/ocs/v2.php/apps/spreed/api/v1/reaction/5ru2tyjj/639
> [HTTP/2 400  45ms]
> 
> 1
> {"ocs":{"meta":{"status":"failure","statuscode":400,"message":""},"data":[]}}
> ```


can you enable [debug logging](https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/logging_configuration.html) on your instance so we can have a look at the stack trace? 🙏

**Comment by BehroozAmoozad** [comment]
I already did. nothing appears in the log when grepping for reaction or spreed. what should I be looking for?

The only thing I can see in logs relating to this is from apache `access.log`  

```
192.168.100.232 192.168.100.101 - - [25/Nov/2024:15:30:50 +0330] "POST /ocs/v2.php/apps/spreed/api/v1/reaction/5ru2tyjj/639 HTTP/1.1" 400 77 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:128.0) Gecko/20100101 Firefox/128.0"
192.168.100.232 192.168.100.101 - - [25/Nov/2024:15:34:03 +0330] "POST /ocs/v2.php/apps/spreed/api/v1/reaction/5ru2tyjj/639 HTTP/1.1" 400 77 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:128.0) Gecko/20100101 Firefox/128.0"
192.168.100.232 192.168.100.101 - - [25/Nov/2024:15:34:22 +0330] "POST /ocs/v2.php/apps/spreed/api/v1/reaction/5ru2tyjj/639 HTTP/1.1" 400 77 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:128.0) Gecko/20100101 Firefox/128.0"
192.168.100.232 192.168.100.101 - - [25/Nov/2024:15:43:46 +0330] "POST /ocs/v2.php/apps/spreed/api/v1/reaction/5ru2tyjj/639 HTTP/1.1" 400 77 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:128.0) Gecko/20100101 Firefox/128.0"
192.168.100.232 192.168.100.101 - - [25/Nov/2024:15:43:48 +0330] "POST /ocs/v2.php/apps/spreed/api/v1/reaction/5ru2tyjj/639 HTTP/1.1" 400 77 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:128.0) Gecko/20100101 Firefox/128.0"
192.168.100.232 192.168.100.101 - - [25/Nov/2024:15:43:49 +0330] "POST /ocs/v2.php/apps/spreed/api/v1/reaction/5ru2tyjj/639 HTTP/1.1" 400 77 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:128.0) Gecko/20100101 Firefox/128.0"
192.168.100.232 192.168.100.101 - - [25/Nov/2024:15:43:49 +0330] "POST /ocs/v2.php/apps/spreed/api/v1/reaction/5ru2tyjj/639 HTTP/1.1" 400 77 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:128.0) Gecko/20100101 Firefox/128.0"
192.168.100.232 192.168.100.101 - - [25/Nov/2024:15:44:01 +0330] "POST /ocs/v2.php/apps/spreed/api/v1/reaction/5ru2tyjj/1154 HTTP/1.1" 400 77 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:128.0) Gecko/20100101 Firefox/128.0"
192.168.100.232 192.168.100.101 - - [25/Nov/2024:15:46:25 +0330] "POST /ocs/v2.php/apps/spreed/api/v1/reaction/5ru2tyjj/1154 HTTP/1.1" 400 77 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:128.0) Gecko/20100101 Firefox/128.0"
192.168.100.232 192.168.100.101 - - [25/Nov/2024:15:46:28 +0330] "POST /ocs/v2.php/apps/spreed/api/v1/reaction/5ru2tyjj/1154 HTTP/1.1" 400 77 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:128.0) Gecko/20100101 Firefox/128.0"
192.168.100.232 192.168.100.101 - - [25/Nov/2024:15:46:29 +0330] "POST /ocs/v2.php/apps/spreed/api/v1/reaction/5ru2tyjj/1154 HTTP/1.1" 400 77 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:128.0) Gecko/20100101 Firefox/128.0"
192.168.100.232 192.168.100.101 - - [25/Nov/2024:15:46:30 +0330] "POST /ocs/v2.php/apps/spreed/api/v1/reaction/5ru2tyjj/1154 HTTP/1.1" 400 77 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:128.0) Gecko/20100101 Firefox/128.0"

```

First column is X-Forwarded-For

**Comment by miaulalala** [comment]
Seems like the forwarding of reactions doesn't work properly. Can you please open a new ticket with this info (as the original issue is unrelated) and fill out the issue template with the proper details? Thanks! 🙏

**Comment by BehroozAmoozad** [comment]
Before I open a new issue, I have to ask whether you are referring to http forwarding or message forwarding or something internal in spreed/nextcloud since http is working fine for video calls with STUN/TURN and these are reactions on normal messages not working.

**Comment by miaulalala** [comment]
> Before I open a new issue, I have to ask whether you are referring to http forwarding or message forwarding or something internal in spreed/nextcloud since http is working fine for video calls with STUN/TURN and these are reactions on normal messages not working.

I mean, forwarding from your IPs - you're using a reverse proxy or something, right?

**Comment by BehroozAmoozad** [comment]
The forwarding is working just fine. In fact, the messages from the log I posted are from the backend server which is serving nextcloud (hence the existence of the X-Forwarded-For header).  The /var/log/nextcloud file also contains a lot of other messages, just none related to reactions.
