### ISSUE TITLE
Avatar menu in conversation can only be opened once

### ISSUE THREAD

**Issue by SystemKeeper** [nextcloud/spreed#9006]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Join a conversation
2. Click on another participants avatar

### Expected behaviour
The "avatar menu" should open each time it's clicked

### Actual behaviour
It only works on the first click

https://user-images.githubusercontent.com/1580193/223981465-69999a1e-3577-4915-a314-bf6b333a2447.mov

## Talk app

**Talk app version:** c.nc.c & sermo.

This is found on the console. So not really sure if it's a problem on our side or on the cue-lib side?!
```
focus-trap.esm.js:328 Uncaught (in promise) Error: Your focus-trap must have at least one container with at least one tabbable node in it at all times
    at h (focus-trap.esm.js:328:13)
    at Object.activate (focus-trap.esm.js:590:9)
    at NcAvatar.js:2:9477
    at p (NcAvatar.js:2:2549)
    at Generator.<anonymous> (NcAvatar.js:2:3886)
    at Generator.next (NcAvatar.js:2:2912)
    at c (NcAvatar.js:2:8537)
    at o (NcAvatar.js:2:9631)
```

**Comment by SystemKeeper** [comment]
The same happens on social if I access the timeline at `apps/social/timeline/timeline` and open a menu of a user. So guess it's safe to assume we are not the problem here.

**Comment by nickvergessen** [comment]
I guess the problem is the findOne endpoint that @ShGKme also had issues with

**Comment by nickvergessen** [comment]
Also happens at https://nextcloud-vue-components.netlify.app/#/Components/NcAvatar with "Avatar with preloaded status"
